def print_num(n):
    print(n, end = '')
print(8, end = '')
print(8, end = '')
print(0, end = '')
print(0, end = '')
print(5, end = '')
print(5, end = '') 
print(5, end = '')  
print(3, end = '')
print(5, end = '')
print(3, end = '')
print(5, end = '')
